### ISSUE TITLE
circe-color-nicks + circe-highlight-nick conflict

### ISSUE THREAD

**Issue by retroj** [jorgenschaefer/circe#54]
A user reported that circe-highlight-nick does not work when circe-color-nicks is enabled (`circe-highlight-nick-type` is 'sender, and `circe-color-nicks-everywhere` is t).  The face applied by circe-color-nicks overrides that applied by circe-highlight-nick.

The likely cause of this is that both circe-highlight-nick and circe-color-nicks run on `lui-pre-output-hook`, and both affect some of the same text, so the behavior is dependent on the order in which they run.  Additionally, circe-color-nicks uses `put-text-property 'face` to set the color, so it will clobber any face that was earlier set on the text; if circe-color-nicks runs after circe-highlight-nick, then circe-highlight-nick-face will be removed from the text, which will break tracking.

So there are two problems with circe-color-nicks.  The first is the precedence problem which determines the final color of nicks, and the second is the face-clobbering problem that breaks tracking.  The second is surely a bug; the first needs further investigation to see if there is a better way of arranging things.

**Comment by jorgenschaefer** [comment]
@TaylanUB, is this fixed in the current version of circe color nicks? I do not use it, so not sure :-)

**Comment by TaylanUB** [comment]
Jorgen Schäfer <notifications@github.com> writes:

> @TaylanUB, is this fixed in the current version of circe color nicks?
> I do not use it, so not sure :-)
>
> —
> Reply to this email directly or view it on GitHub.

It still uses `put-text-property` to set the `face`, so I assume the
described bug still applies.  What would be the right thing to do
instead of using `put-text-property` to set the `face`?  I can apply a
hotfix independent of my `nick-colors` branch.

Taylan

**Comment by jorgenschaefer** [comment]
If there's already a face specified anywhere in the string, it should append the new face, not override it, I think. `circe-merge-text-properties` does the right thing, so that should be simple.

**Comment by TaylanUB** [comment]
Should be fixed by 0674758.
(Forgot to use that "closes #blah" thing.)

**Comment by jorgenschaefer** [comment]
Very nice, thank you!
